### ISSUE TITLE
bug: non-comptent Dockerfile

### ISSUE THREAD

**Issue by DarthBenro008** [sorobix/wasm-handler#2]
The dockerfile of this project does not support rust compiling

The dockerfile has outdated alpine with no rustup support

![image](https://github.com/sorobix/wasm-handler/assets/31009634/ffaaf969-5f56-4198-bc43-d05fc2d39212)

**Comment by ShubhamPalriwala** [comment]
closed in bb8f344c1efe2024742b366a03785dcae98d697d
