### ISSUE TITLE
bug: wasm not b64 encoded!

### ISSUE THREAD

**Issue by DarthBenro008** [sorobix/wasm-handler#3]
The wasm file should be b64 encoded and not json encoded!

https://github.com/sorobix/wasm-handler/blob/fe491046092822a0c0def9cd0025d111df8837ec/wasm_builder.go#L65-L75

This caused a decoding issue on rust side.

![image](https://github.com/sorobix/wasm-handler/assets/31009634/846c6d88-8b39-41d4-bce9-38f6a79fdb42)

**Comment by ShubhamPalriwala** [comment]
fixed in https://github.com/sorobix/wasm-handler/commit/da82e31c3be9969c7b889d6ea4433ab54122d08f
