### ISSUE TITLE
bug: Compilation fails if the project name in `Cargo.toml` is not "sorobix_temp"

### ISSUE THREAD

**Issue by DarthBenro008** [sorobix/wasm-handler#6]
- The compilation fails, if the `cargo.toml` file passed has a different project name

## Potential Bug

This is probably because it cannot find the wasm file with a different project name

**Comment by ShubhamPalriwala** [comment]
it is how it was, it will be the same for now!
the user does not have a need to set the project name as of now! frontend can hard-code it and send.

this will be a separate feature impl when need arises

**Comment by DarthBenro008** [comment]
reopening as discussed

**Comment by ShubhamPalriwala** [comment]
closed in [7772f30](https://github.com/sorobix/wasm-handler/commit/7772f30303d1f82b8e0440a4a3db3fcd3130a2a9)
